In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
##Loading all data

data1 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/01_Sales_Jan.csv')
data2 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/02_Sales_Feb.csv')
data3 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/03_Sales_Mar.csv')
data4 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/04_Sales_Apr.csv')
data5 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/05_Sales_May.csv')
data6 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/06_Sales_Jun.csv')
data7 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/07_Sales_Jul.csv')
data8 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/08_Sales_Aug.csv')
data9 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/09_Sales_Sep.csv')
data10 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/10_Sales_Oct.csv')
data11 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/11_Sales_Nov.csv')
data12 = pd.read_csv('/content/drive/MyDrive/Sem2/Techniques in Business Analytics/Data/12_Sales_Dec.csv')

In [ ]:
total_data = pd.concat([data1, data2, data3,data4, data5,data6,data7,data8,data9,data10,data11,data12])
total_data = total_data.reset_index(drop=True)
total_data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,1/05/2019 20:33,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"
...,...,...,...,...,...,...
186889,319990,Lightning Charging Cable,3,14.95,12/11/2020 20:58,"641 Adams St, Portland, OR 97035"
186890,319989,AA Batteries (4-pack),1,3.84,12/01/2020 12:01,"235 Spruce St, Portland, OR 97035"
186891,319988,Vareebadd Phone,2,400,12/09/2020 6:43,"273 Wilson St, Seattle, WA 98101"
186892,319987,Wired Headphones,1,11.99,12/03/2020 10:39,"778 River St, Dallas, TX 75001"
186893,319986,Bose SoundSport Headphones,1,99.99,12/21/20 21:45,"747 Chestnut St, Los Angeles, CA 90001"

In [ ]:
##Checking the data type of each variable

total_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186894 entries, 0 to 186893
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186346 non-null  object
 1   Product           186346 non-null  object
 2   Quantity Ordered  186345 non-null  object
 3   Price Each        186346 non-null  object
 4   Order Date        186346 non-null  object
 5   Purchase Address  186345 non-null  object
dtypes: object(6)
memory usage: 8.6+ MB

So we have observed that there are few variables which are not supposed to be Object type but they are. We will look into the varibles now

1. Quantity Ordered
2. Price Each
3. Order Date


Second step will be to handle NULL Values
There are NULL values present in each of the column.

We will do some further cleaning by analysing the Purchase Address and getting more details out of it

## 1. Quantity Ordered

In [ ]:
total_data.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,1/05/2019 20:33,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"

In [ ]:
## Let us check the unique values of Quantity Ordered

total_data['Quantity Ordered'].value_counts()

Quantity Ordered
1                   168577
2                    13331
3                     2923
4                      807
Quantity Ordered       355
5                      238
6                       80
7                       24
8                        5
9                        3
0                        1
9999                     1
Name: count, dtype: int64

So we can see that there are some disprencies in the data and that is the reason we have object type in the data type of the column.

Some issues noticed as of now
1. Quantity Ordered is used as value too in some cases
2. 1 order is having 0 Quantity Ordered
3. 1 order is having 9999 Quantity Ordered

In [ ]:
## Let us solve the issue with 0 order and 9999 order

total_data[(total_data['Quantity Ordered']=='0')|(total_data['Quantity Ordered']=='9999')]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
21767,112112,iPhone,0,0,03/15/19 23:05,NaN
99538,236221,##system error##,9999,9999,07/20/19 21:16,"514 Macquarie St, Atlanta, GA 30301"

By looking at the data we can clearly see that these two rows does not make any sense. These rows can be removed from the data

In [ ]:
## Removing the above two rows

total_data = total_data.drop(total_data[(total_data['Quantity Ordered']=='0')|(total_data['Quantity Ordered']=='9999')].index).reset_index(drop=True)

In [ ]:
## We will look into second issue - Quantity Ordered as a row value

#Let us check different values in other columns when row value for Quantity Ordered is Quantity Ordered

for col in total_data.columns:
  if col == 'Quantity Ordered':
    pass
  else:
    print(total_data[total_data['Quantity Ordered']=='Quantity Ordered'][col].unique())

['Order ID']
['Product']
['Price Each']
['Order Date']
['Purchase Address']

So it is clear that these values have been in the dataset due to some technical or human error. These were not meant to be here. Removing again these value does not have any impact on data quality.

In [ ]:
## Removing the above two rows

total_data = total_data.drop(total_data[total_data['Quantity Ordered']=='Quantity Ordered'].index).reset_index(drop=True)

In [ ]:
total_data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,1/05/2019 20:33,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"
...,...,...,...,...,...,...
186532,319990,Lightning Charging Cable,3,14.95,12/11/2020 20:58,"641 Adams St, Portland, OR 97035"
186533,319989,AA Batteries (4-pack),1,3.84,12/01/2020 12:01,"235 Spruce St, Portland, OR 97035"
186534,319988,Vareebadd Phone,2,400,12/09/2020 6:43,"273 Wilson St, Seattle, WA 98101"
186535,319987,Wired Headphones,1,11.99,12/03/2020 10:39,"778 River St, Dallas, TX 75001"
186536,319986,Bose SoundSport Headphones,1,99.99,12/21/20 21:45,"747 Chestnut St, Los Angeles, CA 90001"

## Price Each

In [ ]:
total_data['Price Each'].value_counts()

Price Each
11.95      21904
14.95      21661
2.99       20645
3.84       20579
11.99      18888
150        15462
99.99      13330
149.99      7506
700         6808
600         6285
389.99      6230
379.99      6183
300         4783
1700        4703
999.99      4131
109.99      4101
400         2058
600.0        554
150.0         92
700.0         35
1700.0        21
300.0         18
400.0          8
999999         1
$149.99        1
9999           1
$11.95         1
Name: count, dtype: int64

Apart from NULL values we can see there are three major issues
1. Price Each is having 9999 as one value - It can be an issue or not which needs to be checked
2. $ in front of 2 values
3. nan values in 548 rows - These are not NULL values these are nan values.


Let us check them one after other

In [ ]:
## 1. Price of 9999

total_data[total_data['Price Each']=='9999']

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
9715,150509,### syste error###,NaN,9999,02/26/19 19:53,"921 6th St, Seattle, WA 98101"

CLearly this value again does not make sense and removing this is best solution.

In [ ]:
total_data[(total_data['Price Each']=='$149.99')|(total_data['Price Each']=='$11.95')]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
21,141255,USB-C Charging Cable,1,$11.95,1/09/2019 20:55,"764 11th St, Los Angeles, CA 90001"
36987,176623,27in FHD Monitor,1,$149.99,04/20/19 23:51,"807 12th St, Atlanta, GA 30301"

By looking at the data we got to know that these products have same price in each row but the only issue here is $ sign, which can be removed.

In [ ]:
total_data['Price Each'] = total_data['Price Each'].apply(lambda x: str(x).replace('$',''))

In [ ]:
total_data.iloc[21]

Order ID                                        141255
Product                           USB-C Charging Cable
Quantity Ordered                                     1
Price Each                                       11.95
Order Date                             1/09/2019 20:55
Purchase Address    764 11th St, Los Angeles, CA 90001
Name: 21, dtype: object

Now we will remove the 3rd issue - Handling rows with nan values

In [ ]:
total_data[total_data['Price Each']=='nan']

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
664,NaN,NaN,NaN,nan,NaN,NaN
678,NaN,NaN,NaN,nan,NaN,NaN
797,NaN,NaN,NaN,nan,NaN,NaN
876,NaN,NaN,NaN,nan,NaN,NaN
1296,NaN,NaN,NaN,nan,NaN,NaN
...,...,...,...,...,...,...
184372,NaN,NaN,NaN,nan,NaN,NaN
184718,NaN,NaN,NaN,nan,NaN,NaN
185403,NaN,NaN,NaN,nan,NaN,NaN
186135,NaN,NaN,NaN,nan,NaN,NaN
186522,NaN,NaN,NaN,nan,NaN,NaN

Even these rows does not any specific pattern, all the values are due to some technical issue. So we can remove them

In [ ]:
total_data = total_data.drop(total_data[total_data['Price Each']=='nan'].index).reset_index(drop=True)

In [ ]:
total_data['Price Each'].value_counts()

Price Each
11.95     21905
14.95     21661
2.99      20645
3.84      20579
11.99     18888
150       15462
99.99     13330
149.99     7507
700        6808
600        6285
389.99     6230
379.99     6183
300        4783
1700       4703
999.99     4131
109.99     4101
400        2058
600.0       554
150.0        92
700.0        35
1700.0       21
300.0        18
400.0         8
9999          1
999999        1
Name: count, dtype: int64

## Order Date

In [ ]:
total_data['month'] = pd.to_datetime(total_data['Order Date']).dt.month
total_data['date'] = pd.to_datetime(total_data['Order Date']).dt.date
total_data['year'] = pd.to_datetime(total_data['Order Date']).dt.year
total_data['day'] = pd.to_datetime(total_data['Order Date']).dt.day

In [ ]:
print(total_data['year'].value_counts(normalize=True))
total_data['year'].value_counts()

year
2019    0.999618
2020    0.000258
2021    0.000113
2028    0.000005
2001    0.000005
Name: proportion, dtype: float64

year
2019    185918
2020        48
2021        21
2028         1
2001         1
Name: count, dtype: int64

We have total 5 unique years in the data. But 99.9% of our data belong to just one year.

We need to analyse the rest of 4 years.

2 of them have just 1 record each.

In [ ]:
total_data[total_data['year']==2001]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,month,date,year,day
160996,295123,ThinkPad Laptop,1,999.99,12/28/01 17:19,"866 Pine St, Boston, MA 02215",12,2001-12-28,2001,28

In [ ]:
total_data[total_data['year']==2028]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,month,date,year,day
143418,278809,ThinkPad Laptop,1,2.99,11/17/28 12:38,"969 13th St, Dallas, TX 75001",11,2028-11-17,2028,17